"""delite_delivery_address

Revision ID: 881a9337d57e
Revises: 78b2f17f67ee
Create Date: 2026-05-08 21:07:07.905807

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "881a9337d57e"
down_revision: Union[str, Sequence[str], None] = "78b2f17f67ee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "delivery_address")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders",
        sa.Column(
            "delivery_address",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
